typography_spectrum: 0.4927
color:
  brandColors:
    - '#95c7f8'
    - '#db6b2c'
    - '#11120c'
    - '#5a2619'
    - '#394e61'
  brandStrength: 0.25
  lightness: 0.25
  saturation: 0.4375
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: UA-59790057-1
  facebook: null
  twitter: null
name: funkysoulzh
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: everything wordpress and tech related
description: and some random ramblings
purpose: []
