name: funkysoulzh
favicon: null
layout_spectrum: 0.4923
typography_spectrum: 0.4927
title: everything wordpress and tech related
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-59790057-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#95c7f8'
    - '#db6b2c'
    - '#11120c'
    - '#5a2619'
    - '#394e61'
  brandStrength: 0.25
  lightness: 0.25
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
